### ISSUE TITLE
musl 1.2 build failure

### ISSUE THREAD

**Issue by lucize** [vmware/open-vm-tools#430]
having this problem with musl 1.2.0

```
In file included from /home/build/proxy/staging_dir/target-i386_pentium4_musl/usr/include/glib-2.0/glib.h:62,
                 from /home/build/proxy/build_dir/target-i386_pentium4_musl/open-vm-tools-11.1.0-16036546/lib/include/vmware/tools/utils.h:46,
                 from hgfsServerInt.h:73,
                 from hgfsServerLinux.c:57:
hgfsServerLinux.c: In function 'HgfsStatToFileAttr':
hgfsServerInt.h:64:25: error: called object is not a function or function pointer
 #define LGPFX_FMT       "%s:%s:"
                         ^~~~~~~~
/home/build/proxy/staging_dir/target-i386_pentium4_musl/usr/include/glib-2.0/glib/gmessages.h:345:32: note: in definition of macro 'g_debug'
                                __VA_ARGS__)
                                ^~~~~~~~~~~
hgfsServerInt.h:96:16: note: in expansion of macro 'LGPFX_FMT'
          Debug(LGPFX_FMT fmt, LGPFX, __FUNCTION__, ##__VA_ARGS__); \
                ^~~~~~~~~
hgfsServerLinux.c:2565:4: note: in expansion of macro 'LOG'
    LOG(4, ("access: %jd/%"FMT64"u \nwrite: %jd/%"FMT64"u \n"
    ^~~
make[6]: *** [Makefile:509: hgfsServerLinux.lo] Error 1
make[5]: *** [Makefile:498: all-recursive] Error 1
make[4]: *** [Makefile:543: all-recursive] Error 1
make[3]: *** [Makefile:122: /home/build/proxy/build_dir/target-i386_pentium4_musl/open-vm-tools-11.1.0-16036546/.built] Error 2
make[2]: *** [package/Makefile:113: package/feeds/packages/open-vm-tools/compile] Error 2

```

**Comment by oliverkurth** [comment]
Can you please share more details about the build, like distribution used and compiler version?

**Comment by lucize** [comment]
I'm using openwrt sdk using gcc 8.4.0 for a 32-bit target (for mirroring a real machine)
musl 1.2.0 changes time_t for 32-bit archs to a 64-bit type
also used two patches from openembedded

https://github.com/openembedded/meta-openembedded/blob/master/meta-oe/recipes-support/open-vm-tools/open-vm-tools/0001-Make-HgfsConvertFromNtTimeNsec-aware-of-64-bit-time_.patch

https://github.com/openembedded/meta-openembedded/blob/master/meta-oe/recipes-support/open-vm-tools/open-vm-tools/0002-hgfsServerLinux-Consider-64bit-time_t-possibility.patch

**Comment by oliverkurth** [comment]
I need some more help here to reproduce. I installed a container that holds the sdk from here: https://hub.docker.com/r/openwrtorg/sdk , then followed the instructions. It does not contain an open-vm-tools package. Where can I find that, and how do I get it into the SDK?

**Comment by lucize** [comment]
easyer is to https://openwrt.org/docs/guide-developer/quickstart-build-images
after selecting open-vm-tools in `make menuconfig`
apply https://github.com/openwrt/openwrt/pull/3004
make prepare -j<num_cpu>
make package/open-vm-tools/compile V=s -j<num_cpu>

**Comment by oliverkurth** [comment]
I am hitting this error now:

```In file included from /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/sys/glibc-types.h:4,
                 from /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/features.h:46,
                 from /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/sys/types.h:7,
                 from /home/vmware/openwrt/staging_dir/target-i386_pentium4_musl/usr/include/tirpc/rpc/types.h:41,
                 from /home/vmware/openwrt/build_dir/target-i386_pentium4_musl/open-vm-tools-11.1.0-16036546/lib/include/vmxrpc.h:29,
                 from nicinfo.h:9,
                 from nicinfo_xdr.c:6:
/home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/sys/cdefs.h:1:2: error: #warning usage of non-standard #include <sys/cdefs.h> is deprecated [-Werror=cpp]
 #warning usage of non-standard #include <sys/cdefs.h> is deprecated
  ^~~~~~~
cc1: all warnings being treated as errors
```

which does seem to be related to open-vm-tools.

**Comment by lucize** [comment]
yes, it's strange, maybe try first a make V=s -jX, maybe some dependencies are missing and make prepare is doing something weird
I've made builds on ubuntu 18.04+ and debian 8+

**Comment by oliverkurth** [comment]
I get the same error in another package for `make`:
```
In file included from /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/sys/glibc-types.h:4,
                 from /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/features.h:46,
                 from /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/stdio.h:8,
                 from /home/vmware/openwrt/build_dir/target-i386_pentium4_musl/libnl-tiny-2019-10-29-0219008c/include/netlink-local.h:18,
                 from /home/vmware/openwrt/build_dir/target-i386_pentium4_musl/libnl-tiny-2019-10-29-0219008c/attr.c:12:
/home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/sys/cdefs.h:1:2: error: #warning usage of non-standard #include <sys/cdefs.h> is deprecated [-Werror=cpp]
```

I am unable to investigate this if I don't have an environment to reproduce your issue. I need reliable steps to reproduce the issue at hand, I don't have the time to deal with unrelated other problems. Let me know when you have that.

**Comment by lucize** [comment]
can you tell me on what os are you trying to build ?

**Comment by oliverkurth** [comment]
It's a Ubuntu 18.04 VM, just like yours.

**Comment by lucize** [comment]
ok, I'll start an empty one and see if I get this

**Comment by lucize** [comment]
maybe the patch wasn't applyed correctly ?

*netboot install -selected only openssh-server

```
sudo apt-get install build-essential libncursesw5-dev python unzip   
sudo apt install git awk ncurses-dev gettext
git clone https://git.openwrt.org/openwrt/openwrt.git
cd openwrt
./scripts/feeds update -a
./scripts/feeds install -a
wget https://github.com/openwrt/openwrt/pull/3004.patch
patch -p1 < 3004.patch
make menuconfig

```
*selected x86 generic
*selected open-vm-tools, save on exit

*make sure this runs ok (enough ram or remove the -j option)
`make prepare -j8`

final output:
[...]
 make[3] -C toolchain/gcc/final compile
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] buildinfo
 make[3] diffconfig buildversion feedsversion

*V=1 prints only warnings and errors
`make package/open-vm-tools/compile V=1 -j8`

final output:

```
/home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/lib/gcc/i486-openwrt-linux-musl/8.4.0/../../../../i486-openwrt-linux-musl/bin/ar: `u' modifier ignored since `D' is the default (see `U')
In file included from /home/vmware/openwrt/build_dir/target-i386_pentium4_musl/open-vm-tools-11.1.0-16036546/lib/include/hgfs.h:59,
                 from /home/vmware/openwrt/build_dir/target-i386_pentium4_musl/open-vm-tools-11.1.0-16036546/lib/include/hgfsUtil.h:63,
                 from hgfsUtil.c:47:
hgfsUtil.c: In function 'HgfsConvertFromNtTimeNsec':
/home/vmware/openwrt/build_dir/target-i386_pentium4_musl/open-vm-tools-11.1.0-16036546/lib/include/vm_assert.h:331:7: error: static assertion failed: "sizeof (unixTime->tv_sec) == 4"
       _Static_assert(e, #e); \
       ^~~~~~~~~~~~~~
hgfsUtil.c:118:4: note: in expansion of macro 'ASSERT_ON_COMPILE'
    ASSERT_ON_COMPILE(sizeof (unixTime->tv_sec) == 4);
    ^~~~~~~~~~~~~~~~~
make[5]: *** [hgfsUtil.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [/home/vmware/openwrt/build_dir/target-i386_pentium4_musl/open-vm-tools-11.1.0-16036546/.built] Error 2
make[1]: *** [package/feeds/packages/open-vm-tools/compile] Error 2
make -r package/open-vm-tools/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/home/vmware/openwrt/include/toplevel.mk:222: recipe for target 'package/open-vm-tools/compile' failed
make: *** [package/open-vm-tools/compile] Error 1

```

**Comment by oliverkurth** [comment]
Okay, I see that same error now. Not sure what went wrong the first time.

**Comment by oliverkurth** [comment]
I could apply the patch `0001-Make-HgfsConvertFromNtTimeNsec-aware-of-64-bit-time_.patch`,after fixing the path (remove `open-vm-tools`) and copying it to the `patches` dir, but the second patch did not apply. So I get the error that patch was supposed to fix.

But looks like I have an environment now to test. I will file an internal bug and let the owner of that code know.

**Comment by lucize** [comment]
for the second patch you have to adjust the tabs or something like that

**Comment by neheb** [comment]
> I am hitting this error now:
> 
> ```
>                  from /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/features.h:46,
>                  from /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/sys/types.h:7,
>                  from /home/vmware/openwrt/staging_dir/target-i386_pentium4_musl/usr/include/tirpc/rpc/types.h:41,
>                  from /home/vmware/openwrt/build_dir/target-i386_pentium4_musl/open-vm-tools-11.1.0-16036546/lib/include/vmxrpc.h:29,
>                  from nicinfo.h:9,
>                  from nicinfo_xdr.c:6:
> /home/vmware/openwrt/staging_dir/toolchain-i386_pentium4_gcc-8.4.0_musl/include/sys/cdefs.h:1:2: error: #warning usage of non-standard #include <sys/cdefs.h> is deprecated [-Werror=cpp]
>  #warning usage of non-standard #include <sys/cdefs.h> is deprecated
>   ^~~~~~~
> cc1: all warnings being treated as errors
> ```
> 
> which does seem to be related to open-vm-tools.

I will note that I removed sys/cdefs.h from that PR. musl does not include sys/cdefs.h as it is a legacy header. It was only added to the OpenWrt package to prevent compilation issues.

I have since patched many of those issues. I don't believe I've tested open-vm-tools though.

**Comment by nuclearfall** [comment]
try to use -Wno_deprecated flag to inhibit warnings? Compiler is treating all warnings as errors. You can inhibit behavior altogether with -w, but it's not recommended. Musl is not intended library to use.

So, I hope you are successful with musl. It would be good news.

**Comment by neheb** [comment]
Right. Unfortunately upstream doesn't seem to like patches.
