### ISSUE TITLE
Build against glibc-2.43 fails due to -Werror=discarded-qualifiers

### ISSUE THREAD

**Issue by heitbaum** [vmware/open-vm-tools#782]
### Describe the bug

```c

../../../lib/hgfs/hgfsEscape.c: In function 'HgfsAddEscapeCharacter':
../../../lib/hgfs/hgfsEscape.c:201:15: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  201 |       illegal = strchr(HGFS_ILLEGAL_CHARS, bufIn[escapeContext->processedOffset]);
      |               ^
../../../lib/hgfs/hgfsEscape.c: In function 'HgfsIsEscapeSequence':
../../../lib/hgfs/hgfsEscape.c:586:21: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  586 |          substitute = strchr(HGFS_SUBSTITUTE_CHARS, bufIn[offset - 2]);
      |                     ^
../../../lib/hgfs/hgfsEscape.c:591:18: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  591 |       substitute = strchr(HGFS_SUBSTITUTE_CHARS, bufIn[offset - 1]);
      |                  ^
../../../lib/hgfs/hgfsEscape.c: In function 'HgfsEscapeUndoComponent':
../../../lib/hgfs/hgfsEscape.c:890:29: error: initialization discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  890 |          char* substitute = strchr(HGFS_SUBSTITUTE_CHARS, bufIn[offset - 1]);
      |                             ^~~~~~

``` 

### Reproduction steps

1. Build against glibc-2.43

### Expected behavior

Successful compile

**Comment by pngzhencao-bc** [comment]
Thanks for your suggested fix and we'll review.

Could you provide more info about what Linux distro you are using? Is it ubuntu26.04?
We'll create a local test environment to check the fix.

**Comment by heitbaum** [comment]
Our build server is 26.04 (but the glibc 2.43 is compiled as part of our Cross Compiled Packaging framework.) The issue should be evident when compiling against 2.43.

**Comment by heitbaum** [comment]
How we do our builds: https://github.com/LibreELEC/LibreELEC.tv/blob/master/tools/docker/README.md

```
git clone https://github.com/LibreELEC/LibreELEC.tv.git
cd LibreELEC.tv
sed -i -e "s/RUN useradd docker/RUN useradd docker -o -u $(id -u)/" tools/docker/resolute/Dockerfile
docker build --pull -t opvm tools/docker/resolute
docker run --rm --log-driver none -v `pwd`:/build -w /build -it opvm bash

sed -i -e 's/PKG_VERSION=.*/PKG_VERSION="2.43"/' packages/devel/glibc/package.mk
CHANGE_HASH=yes scripts/get glibc
scripts/build open-vm-tools ## This will cause the failure.
```

To build with 2.42, adjust the `packages/devel/glibc/package.mk`, then `make clean` and build the `scripts/build open-vm-tools`

**Comment by pngzhencao-bc** [comment]
OK.Thanks for your input and the problem is clear and the fix is straight forward. 
Broadcom now has some updated process and document work needed before we could adopt your patch. I'll get back to you once I am clear about the process.

**Comment by heitbaum** [comment]
> OK.Thanks for your input and the problem is clear and the fix is straight forward. Broadcom now has some updated process and document work needed before we could adopt your patch. I'll get back to you once I am clear about the process.

Any update? Anything I can assist with.

**Comment by pngzhencao-bc** [comment]
> > OK.Thanks for your input and the problem is clear and the fix is straight forward. Broadcom now has some updated process and document work needed before we could adopt your patch. I'll get back to you once I am clear about the process.
> 
> Any update? Anything I can assist with.

We are still awaiting updated legal process from Broadcom.  Thanks for the patience.

**Comment by P3p111n0** [comment]
Hi, any update on this?

**Comment by heitbaum** [comment]
@pngzhencao-bc any progress on having this merged?
