### ISSUE TITLE
Fails to build with openssl 4.0

### ISSUE THREAD

**Issue by yselkowitz** [vmware/open-vm-tools#794]
### Describe the bug

open-vm-tools 13.1.0 FTBFS with openssl 4.0, as in Fedora rawhide:

```
../common/certverify.c: In function 'CertVerify_CheckSignatureUsingCert':
../common/certverify.c:806:15: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  806 |    x509PubKey = X509_get_X509_PUBKEY(cert);
      |               ^
../common/certverify.c: In function 'FindCert':
../common/certverify.c:938:12: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  938 |          v = X509_get_subject_name(c);
      |            ^
../common/certverify.c:940:12: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  940 |          v = X509_get_issuer_name(c);
      |            ^
../common/certverify.c: In function 'CertVerify_CheckForUnrelatedCerts':
../common/certverify.c:1004:12: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 1004 |    subject = X509_get_subject_name(baseCert);
      |            ^
../common/certverify.c:1009:15: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 1009 |       subject = X509_get_subject_name(curCert);
      |               ^
../common/certverify.c:1016:11: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 1016 |    issuer = X509_get_issuer_name(baseCert);
      |           ^
../common/certverify.c:1021:14: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 1021 |       issuer = X509_get_issuer_name(curCert);
      |              ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:715: libvgauth_la-certverify.lo] Error 1
```

### Reproduction steps

1. Build with open-vm-tools, e.g. in Fedora rawhide

### Expected behavior

Code compiles.

### Additional context

This is covered in https://github.com/openssl/openssl/releases/tag/openssl-4.0.0, specifically:

* Signatures of numerous API functions, including those that are related
to X509 processing, are changed to include const qualifiers for argument
and return types, where suitable.

The fix is simple and backwards compatible.

**Comment by yselkowitz** [comment]
Downstream fix: https://src.fedoraproject.org/rpms/open-vm-tools/pull-request/15

**Comment by PaTHml** [comment]
Thanks for reporting this issue.

I have filed an internal bug.
