### ISSUE TITLE
unable to build on freebsd 11.2

### ISSUE THREAD

**Issue by urtec** [vmware/open-vm-tools#475]
unable to build on freebsd 11.2
`../open-vm-tools-11.2.0-16938113/libvmtools/vmtools.c:44: multiple definition of `vm_version'
vmtoolsd-mainPosix.o:/usr/home/test/open-vm-tools-11.2.0-16938113/services/vmtoolsd/mainPosix.c:47: first defined here
collect2: error: ld returned 1 exit status`

**Comment by johnwvmw** [comment]
@urtec  You did not provide the command sequence used to do the build of 11.2.0 open-vm-tools, but I was able to reproduce your reported failure by simply doing the **./configure** followed by a **make**.

Please restart the process.  After extraction from the tar file, run the command 
   **autoreconf -f -i** 
before running the **./configure** command.  This will rebuild the autoconf, automake and libtool scripts as needed.   My build completes as expected by doing the sutoreconf firts.

You may also want to take a look at the FreeBSD specific patches that are used in the FreeBSD /usr/ports build of open-vm-tools at https://svnweb.freebsd.org/ports/branches/2020Q4/emulators/open-vm-tools/files/

If you encounter any further problems, please provide the complete command sequence used.

Thanks.

**Comment by urtec** [comment]
the sequence is (no difference without the switches though)
`./configure --without-gtkmm3 --without-gtk3`

I did `autoreconf -f -i` first now have another error:

.libs/libdndcp_la-dndUIX11.o:/usr/local/lib/gcc9/include/c++/bits/predefined_ops.h:241: more undefined references to `Glib::ustring::ustring(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
*** Error code 1

**Comment by johnwvmw** [comment]
Please explain the choice of the ``--without-gtkmm3 --without-gtk3``

What graphical desktop are you planning to use?

**Comment by urtec** [comment]
none as I am using headless one. I try to update the tools since Freebsd guest disk IO on Windows shared folder is much slower than in Linux VMWare guess. And secondly it touches every source file's timestamp when doing cmake build on Windows shared folder. See if these are fixed.

**Comment by johnwvmw** [comment]
Try simply ``--without-x``

**Comment by urtec** [comment]
This works. Thanks.

**Comment by johnwvmw** [comment]
Glad to hear that. 

Closing this issue, please reopen if you encounter any additional build isues.
