### ISSUE TITLE
Unable to build on RHEL/CentOS 6

### ISSUE THREAD

**Issue by scaronni** [vmware/open-vm-tools#37]
I'm trying to update open-vm-tools in epel-6, but the build fails on VGAuth:

```
mv -f .deps/VGAuthService-ticket.Tpo .deps/VGAuthService-ticket.Po
mv -f .deps/VGAuthService-service.Tpo .deps/VGAuthService-service.Po
mv -f .deps/VGAuthService-verify.Tpo .deps/VGAuthService-verify.Po
../serviceImpl/saml.cpp: In function 'bool SAMLCheckSubject(const xercesc_3_0::DOMDocument*, SAMLTokenData&)':
../serviceImpl/saml.cpp:790: error: 'const class xercesc_3_0::DOMElement' has no member named 'getFirstElementChild'
../serviceImpl/saml.cpp:791: error: 'class xercesc_3_0::DOMElement' has no member named 'getNextElementSibling'
../serviceImpl/saml.cpp: In function 'xercesc_3_0::DOMElement* SAMLFindChildByName(const xercesc_3_0::DOMElement*, const char*)':
../serviceImpl/saml.cpp:1218: error: 'const class xercesc_3_0::DOMElement' has no member named 'getFirstElementChild'
../serviceImpl/saml.cpp:1219: error: 'class xercesc_3_0::DOMElement' has no member named 'getNextElementSibling'
make[2]: Leaving directory `/builddir/build/BUILD/open-vm-tools-9.10.2-2822639/vgauth/service'
make[2]: *** [VGAuthService-saml.o] Error 1
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/builddir/build/BUILD/open-vm-tools-9.10.2-2822639/vgauth'
make: *** [all-recursive] Error 1
```

RHEL/CentOS 6 has xerces 3.0, while Fedora and RHEL/CentOS 7 do have 3.1.

**Comment by ravindravmw** [comment]
> RHEL/CentOS 6 has xerces 3.0, while Fedora and RHEL/CentOS 7 do have 3.1.

Sorry we missed this earlier. Is upgrading xerces an option?

**Comment by scaronni** [comment]
I don't think so, xerces-c is an official RHEL package (included in the RHEL installation media) so I highly doubt. Would it be possible to rework the source code to make it work with xerces 3.0?

**Comment by ravindravmw** [comment]
@scaronni 3.0 to 3.1 seems like a minor upgrade to the xerces-c. Would you mind trying it with Red Hat? If upgrading xerces-c turns out to be a non-viable option, disabling vgauth in the build might be a quick and simple solution in the interim. I believe you have already taken that alternate route in Fedora.

We do have plans to rework the code to make it work with libxml2 and xmlsec1, will that help?

**Comment by scaronni** [comment]
Using xmlsec1 and libxml2 would help as long as you give some breadth to the minimum version you require; as anything in RHEL 6 is quite old:

http://koji.fedoraproject.org/koji/packageinfo?packageID=878
http://koji.fedoraproject.org/koji/packageinfo?packageID=723

xmlsec1 is not in RHEL 7 (it is in epel), so probably that needs to be integrated as well before your new version of open-vm-tools will be taken by Red Hat.

Regarding xerces-c, I will try, but I'm pretty sure it will not happen. VGAuth is currently disabled in epel-6.

**Comment by scaronni** [comment]
There has been no feedback here from VMware, but this now works.
I've applied all the changes that you have applied to the 10.1.5 rawhide build to RHEL 6, including the new xmlsec1 dependency. VGAuth builds fine now on RHEL/CentOS 6.

I'm building the EPEL update now.

**Comment by ravindravmw** [comment]
> There has been no feedback here from VMware, but this now works.

Simone, what feedback is needed from VMware? Could you please be specific? Thanks!

**Comment by scaronni** [comment]
The problem in this ticket has been fixed in 10.1.5 but as you can see there has been no update to it, no one mentioned that it was fixed. I actually discovered it from your last commit to the rawhide branch. Just saying.

**Comment by ravindravmw** [comment]
Sorry for the lack of communication on this one. Problem is we don't have an easy way to map github issues with the changes. We are still figuring out a better way to do it. Thanks for closing this issue!
